config/routes.rb
Rails.application.routes.draw do

  resources :attractions

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root to: "welcome#index"
  
  resources :destinations

  resources :users do
    resources :trips, shallow: true
  end

  resources :trips, only: [:index, :show]
end

app/models/destination.rb
class Destination < ActiveRecord::Base

  has_many :trips
  has_many :users, :through => :trips
  has_many :attractions

  validates_presence_of :city
  validates :city, format: { with: /\A[a-z0-9\s]+\Z/i,
    message: "uses letters & spaces only, no special characters or numbers" }
  validates :city, length: { minimum: 2}
  before_validation :capitalize

  def popularity
    self.trips.count
  end

  def self.popularity_sort
    Destination.all.sort_by { |destination| destination.popularity}.reverse
  end

  def capitalize
    self.city = self.city.titleize
  end

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController

 before_action :find_destination, only: [:show, :edit, :update, :destroy]

  def index
    @destinations = Destination.all
  end 

  def new
    @destination = Destination.new
  end

  def create
    @destination = Destination.find_or_create_by(destination_params) 

    if @destination.valid?
      @destination.save 
      redirect_to @destination
    else
      render :new
    end

  end

  def show 
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @destination }
    end
  end

  def edit
  end

  def update
    if @destination.update(destination_params)
      flash[:notice] = "Destination successfully updated"
      redirect_to @destination
    else
      flash[:notice] = "Destination can't be blank. Please try again."
      render :edit 
    end
  end

  def destroy
    @destination.destroy
    flash[:notice] = "Destination was deleted" 
    redirect_to destinations_path 
  end

  private

  def destination_params
    params.require(:destination).permit(:city)
  end

  def find_destination
    @destination = Destination.find(params[:id])
  end

end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |destination_builder| %>

   <%= destination_builder.label :city %>
   <%= destination_builder.text_field :city %><br><br>
   
 <%= destination_builder.submit %>
 
<% end %>

app/views/destinations/edit.html.erb
<h3>Edit This Destination</h3>

<%= render "form" %>

app/views/destinations/index.html.erb
<h3>All Destinations</h3>

<% @destinations.popularity_sort.each do |destination| %>

  <ul>
    <li><%= link_to destination.city, destination_path(destination) %> <%= destination.popularity %> Trips Saved <%= link_to "Delete", destination, method: :delete, data: { confirm: "Delete?" } %></li>
  </ul>

<% end %>

app/views/destinations/new.html.erb
<h3>Add a New Destination City</h3>

<% if @destination.errors.any? %>
      <ul>
        <% @destination.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
<% end %>

<%= render "form" %>

app/views/destinations/show.html.erb
<h3><b><%= @destination.city %></h3></b><%= link_to "Edit this City", edit_destination_path(@destination) %><br><br>

<h4>Related Trips</h4>

<% @destination.trips.each do |trip| %>
  <li><%= link_to trip.trip_nickname, trip_path(trip) %> - <%= link_to trip.user.username, user_path(trip.user) %>'s Trip</li>
<% end %><br>

<h4>Attractions in <%= @destination.city %>:</h4>
<% @destination.attractions.each do |attraction| %>
  <li><%= link_to attraction.name, attraction_path(attraction) %></li>
<% end %>

<span class='st_email_large' displayText='Email'></span>
<span class='st_twitter_large' displayText='Tweet'></span>
<span class='st_facebook_large' displayText='Facebook'></span>
<span class='st_pinterest_large' displayText='Pinterest'></span>