config/routes.rb
Rails.application.routes.draw do

  resources :attractions

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root to: "welcome#index"
  
  resources :destinations

  resources :users do
    resources :trips, shallow: true
  end

  resources :trips, only: [:index, :show]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>

  <head>  
    
    <!-- JS & CSS Manifest files -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <script type="text/javascript">var switchTo5x=true;</script>
    
    <!-- ShareThis buttons-->
    <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
    <script type="text/javascript">stLight.options({publisher: "33ef7225-b587-4dbf-8168-d0b0f32a443a", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>

    <title>Vacay</title>
  </head>

  <body>
  <ul class="nav nav-pills">
    <li role="presentation" class="dropdown active">
    <% if user_signed_in? %>
    
      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        Trips <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to('See All Your Trips', user_trips_path(current_user)) %></li>
        <li><%= link_to('Add a New Trip', new_user_trip_path(current_user))%> </li>
      </ul>
    
    <li role="presentation" class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        Destinations <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li> <%= link_to('See All Destinations', destinations_path) %></li>
        <li><%= link_to('New Destination', new_destination_path) %> </li>
      </ul>
    
    <li role="presentation" class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        Attractions <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to('See All Attractions', attractions_path) %></li>
        <li><%= link_to('New Attraction', new_attraction_path) %></li>
      </ul>
      
    <li role="presentation" class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Your Account <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to('Your Profile', user_path(current_user)) %> </li>
        <li><%= link_to('Edit Your Profile', edit_user_path(current_user)) %> </li>
        <li><%= link_to('Log Out', destroy_user_session_path, :method => :delete) %></li>
      </ul>
    <% end %>

  </ul>
  <h1> Vacay </h1>

  <% if user_signed_in? %><br>
    You are signed in as <b><%= current_user.email %></b>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  </body>
  
</html>