config/routes.rb
Rails.application.routes.draw do

  resources :attractions

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root to: "welcome#index"
  
  resources :destinations

  resources :users do
    resources :trips, shallow: true
  end

  resources :trips, only: [:index, :show]
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController

  before_action :find_attraction, only: [:show, :edit, :update, :destroy]

  def index
    @attractions = Attraction.all

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @attractions }
    end
  end

  def new
    @attraction = Attraction.new
  end

  def create
    @attraction = Attraction.create(attraction_params)
    @destination = Destination.find_or_create_by(:city => params[:attraction][:destination][:destination_city])
    @attraction.destination = @destination
   
    if (params[:attraction][:trip][:trip_nickname]) == ""
      @trip = "N/A" # Don't save trip
    else
      @trip = current_user.trips.find_or_create_by(:trip_nickname=> params[:attraction][:trip][:trip_nickname])
      @trip.destination = @destination
      @attraction.trips << @trip
    end
      
    if @attraction.valid?
      @attraction.save
      #redirect_to @attraction
      render json: @attraction, status: 201
    else
      render :new
    end

  end

  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @attraction }
    end
  end

  def edit
  end
  
  def update
    @destination = Destination.find_or_create_by(:city => params[:attraction][:destination][:destination_city]) unless (params[:attraction][:destination][:destination_city]) == ""
    @attraction.update(attraction_params)
    @attraction.destination = @destination

    if (params[:attraction][:trip][:trip_nickname]) == "" || (params[:attraction][:trip][:trip_nickname]) == "N/A"
      @trip = "N/A"
    else
      @trip = current_user.trips.find_or_create_by(:trip_nickname=> params[:attraction][:trip][:trip_nickname])
      @trip.destination = @destination
      @attraction.trips << @trip
    end

    if @attraction.valid?
      flash[:notice] = "Attraction details successfully updated"
      redirect_to @attraction
    else
      flash[:notice] = "Something went wrong. Please try again."
      render :edit
    end

  end

  def destroy
    @attraction.destroy
    flash[:notice] = "Attraction was deleted"
    redirect_to user_trips_path(current_user)
  end

  private

  def attraction_params
    params.require(:attraction).permit(:name, :url, :attraction_type, :destination_city, :trip_nickname)
  end

  def find_attraction
    @attraction = Attraction.find_by_id(params[:id])
    @destination = @attraction.destination
  end

end


  

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/views/attractions/_form.html.erb
<%= form_for(@attraction) do |f| %>

  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <%= f.label :attraction_type %><br>
  <%= f.text_field :attraction_type %><br>

  <%= f.label :url %><br>
  <%= f.text_field :url %><br>

  <%= f.fields_for :destination do |p| %>
    <%= p.label :destination_city %><br>
    <%= p.text_field :destination_city %><br> 
  <% end %>

  <%= f.fields_for :trip do |p| %>
    <%= p.label :trip_nickname %><br>
    <%= p.text_field :trip_nickname %>
  <% end %><br><br>

<%= f.submit%>

<% end %>

app/views/attractions/edit.html.erb
<h3>Edit This Attraction</h3>
<p> Edit this attraction's info or add it to a trip</p>

<%= render "form" %>

app/views/attractions/index.html.erb
<h3>All Attractions</h3>

<% @attractions.each do |attraction| %>
  <ul>
    <li><%= link_to attraction.name, attraction_path(attraction) %> <%= attraction.trips.count %> Trips Saved <%= link_to "Delete", attraction, method: :delete, data: { confirm: "Confirm" } %></li>
  </ul>
<% end %>

app/views/attractions/new.html.erb
<h3>Add an Attraction</h3>
<p> Attraction <b>MUST</b> include Destination City </p>

<% if @attraction.errors.any? %>
      <ul>
        <% @attraction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
<% end %>

<div id = "new-attraction-form">
<%= render "form" %>
</div>

<div id="attraction-footer">
  
  <h3>Attraction Created!</h3>
  <b id="attractionName"></b><br>
  <b id="attractionUrl"></b><br>
  <b id="attractionType"></b><br>
  <b id="attractionCity"></b><br></b><br>

  <span class='st_email_large' displayText='Email'></span>
  <span class='st_twitter_large' displayText='Tweet'></span>
  <span class='st_facebook_large' displayText='Facebook'></span>
  <span class='st_pinterest_large' displayText='Pinterest'></span>

</div>

<script type="text/javascript" charset="utf-8">
  $(function () {
    $('form').submit(function(event) {
      event.preventDefault();
 
      var values = $(this).serialize();
      var posting = $.post('/attractions', values);
     
     posting.done(function(data) {
        var newAttraction = new Attraction(
          data["attraction"]["id"],
          data["attraction"]["name"],
          data["attraction"]["url"],
          data["attraction"]["attraction_type"],
          data["attraction"]["destination"]
          );

        // Set url to include http://www.
        var formattedUrl = newAttraction.formatUrl();
        newAttraction["url"] = formattedUrl;

        $("#attractionName").html("Name: " + "<a href='/attractions/" + newAttraction.id + "'>" + newAttraction["name"] + "</a>");
        $("#attractionUrl").html("Website: " + "<a href='" + newAttraction.url + "'>" + newAttraction["url"] + "</a>");
        $("#attractionName2").html(newAttraction["name"]);
        $("#attractionType").html("Attraction Type: " + newAttraction["attraction_type"]);
        $("#attractionCity").html("City: " + "<a href='/destinations/" + newAttraction["destination"]["id"] + "'>" + newAttraction["destination"]["city"] + "</a>" );
       $("#attraction-footer").css("visibility", "visible"); // show the attraction
      });
    });
  });

  $(document).ready(function() {
      $(".dropdown-toggle").dropdown();
  });
</script>

app/views/attractions/show.html.erb
<h3>Attraction Info</h3>

<b>Name:  </b><%= @attraction.name %><br>
<b>Website: </b><%= link_to @attraction.url, @attraction.url %><br>
<b>Attraction Type: </b><%= @attraction.attraction_type %><br>
<b>City:  </b><%= @attraction.destination.city %><br></b><br>

<h4> These people are interested in <%= @attraction.name %><br><br>

<% @attraction.trips.each do |trip| %>
  <li><%= link_to trip.user.username, user_path(trip.user) %></li>
<% end %>

<br><%= link_to "Edit this Attraction", edit_attraction_path(@attraction) %><br>
<%= link_to "Delete this Attraction", @attraction, method: :delete, data: { confirm: "Delete?"} %></li><br>

<span class='st_email_large' displayText='Email'></span>
<span class='st_twitter_large' displayText='Tweet'></span>
<span class='st_facebook_large' displayText='Facebook'></span>
<span class='st_pinterest_large' displayText='Pinterest'></span>